- name: Create docker challenge dir
  file:
    path: "{{ dir_path.challenge }}/go-app"
    state: directory
  tags: go-docker-challenge

- name: Copy docker challenges
  copy:
    src: "{{ dir_path.docker }}"
    dest: "{{ dir_path.challenge }}/go-app/"
    mode: 0777
  tags: go-docker-challenge
