- name: Create docker exercise dir
  file:
    path: "{{ dir_path.challenge }}/go-app"
    state: directory
  tags: go-docker-exercise

- name: Copy docker exercises
  copy:
    src: "{{ dir_path.docker }}"
    dest: "{{ dir_path.challenge }}/go-app/"
    mode: 0777
  tags: go-docker-exercise
