- name: Setup webserver challenge
  become: yes
  block:

    - name: Create Linux webserver challenge dir in user home
      file:
        path: "/home/{{ ansible_user }}/challenge/linux-webserver"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      tags: linux-webserver-challenge

    - name: Copy challenge files
      copy:
        src: "{{ dir_path.webserver }}/{{ item }}"
        dest: "/home/{{ ansible_user }}/challenge/linux-webserver/{{ item }}"
        mode: '0644'
      with_items:
        - HINTS.md
        - task.txt
      tags: linux-webserver-challenge

    - name: Upload and run webserver init script
      copy:
        src: "{{ dir_path.webserver }}/init-webserver.sh"
        dest: /tmp/init-webserver.sh
        mode: '0755'
      tags: linux-webserver-challenge

    - name: Execute webserver setup
      command: /tmp/init-webserver.sh
      tags: linux-webserver-challenge

    - name: Upload cronjob script
      copy:
        src: "{{ dir_path.webserver }}/cronjob.sh"
        dest: /tmp/cronjob.sh
        mode: '0755'
      tags: linux-webserver-challenge

    - name: Execute cronjob setup
      command: /tmp/cronjob.sh
      tags: linux-webserver-challenge

    - name: Create nginx service override directory
      file:
        path: /etc/systemd/system/nginx.service.d
        state: directory
        mode: '0755'
      tags: linux-webserver-challenge

    - name: Upload nginx hook script
      copy:
        src: "{{ dir_path.webserver }}/nginx-hook.sh"
        dest: /usr/local/bin/nginx-hook.sh
        mode: '0755'
      tags: linux-webserver-challenge

    - name: Create nginx service override
      copy:
        dest: /etc/systemd/system/nginx.service.d/override.conf
        content: |
          [Service]
          ExecStartPost=/usr/local/bin/nginx-hook.sh
          ExecReload=/bin/kill -s HUP $MAINPID
          ExecReloadPost=/usr/local/bin/nginx-hook.sh
      tags: linux-webserver-challenge

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      tags: linux-webserver-challenge

    # Register the challenge path
    - name: Register webserver challenge location
      set_fact:
        webserver_challenge_path: "/home/{{ ansible_user }}/challenge/linux-webserver"
      tags: linux-webserver-challenge

    # Display summary
    - name: Display challenge summary
      debug:
        msg: |
          ✅ Linux Webserver Challenge deployed successfully!
          📁 Challenge location: {{ webserver_challenge_path }}

          To start the challenge:
            cd {{ webserver_challenge_path }}
            cat task.txt
      tags: linux-webserver-challenge
